#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=MasterSub
server:
  port: 9776

Spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/master-sub-productDb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: product-service


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
