server:
  port: 9774

Spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/notificationDb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: notification


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true